name: s2i2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.6.15=py37h06a4308_0
  - cudatoolkit=11.7.0=hd8887f6_10
  - gflags=2.2.2=he1b5a44_1004
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libfaiss=1.7.1=cuda112h5bea7ad_1_cuda
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=15_linux64_openblas
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - numpy=1.21.6=py37h976b520_0
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py37h06a4308_0
  - python=3.7.13=h12debd9_0
  - python_abi=3.7=2_cp37m
  - readline=8.1.2=h7f8727e_1
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - tsnecuda=3.0.1=cuda112py37h589322c_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.2.0
    - accelerate==0.11.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asteroid==0.4.4
    - asteroid-filterbanks==0.4.0
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - audioread==2.1.9
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bitarray==2.6.0
    - bleach==5.0.1
    - cached-property==1.5.2
    - cachetools==5.2.0
    - catalyst==22.4
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - click==8.1.3
    - colorama==0.4.5
    - cycler==0.11.0
    - cython==0.29.30
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - dtw-python==1.1.6
    - easydict==1.9
    - editdistance==0.6.0
    - einops==0.4.1
    - entrypoints==0.4
    - fairseq==0.12.2
    - fastjsonschema==2.16.2
    - ffmpeg-python==0.2.0
    - filelock==3.7.1
    - fonttools==4.34.4
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - future==0.18.2
    - gdown==4.5.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - h5py==3.7.0
    - huggingface-hub==0.8.1
    - hydra-core==1.0.7
    - hydra-slayer==0.4.0
    - hyperpyyaml==1.0.1
    - idna==3.3
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - intervaltree==3.1.0
    - ipykernel==6.16.0
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.16.0
    - julius==0.2.6
    - jupyter==1.0.0
    - jupyter-client==7.4.2
    - jupyter-console==6.4.4
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kaldi-io==0.9.4
    - kiwisolver==1.4.4
    - librosa==0.9.2
    - lightning-bolts==0.5.0
    - llvmlite==0.38.1
    - lxml==4.9.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.6
    - mir-eval==0.7
    - mistune==2.0.4
    - more-itertools==9.0.0
    - multidict==6.0.2
    - nbclient==0.7.0
    - nbconvert==7.2.1
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - nltk==3.7
    - normalise==0.1.8
    - notebook==6.4.12
    - numba==0.55.2
    - oauthlib==3.2.0
    - omegaconf==2.0.6
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pb-bss-eval==0.0.2
    - pesq==0.0.4
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - pooch==1.6.0
    - portalocker==2.5.1
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.31
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydeprecate==0.3.1
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pysndfx==0.3.6
    - pysocks==1.7.1
    - pystoi==0.3.3
    - python-dateutil==2.8.2
    - pytorch-lightning==1.4.2
    - pytorch-ranger==0.1.1
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.3.2
    - qtpy==2.2.1
    - regex==2022.7.25
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - resampy==0.3.1
    - roman==3.3
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - s3prl==0.3.1
    - sacrebleu==2.2.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.0
    - send2trash==1.8.0
    - sentencepiece==0.1.97
    - sentry-sdk==1.8.0
    - setproctitle==1.2.3
    - setuptools==59.5.0
    - shortuuid==1.0.9
    - six==1.16.0
    - smmap==5.0.0
    - sortedcontainers==2.4.0
    - soundfile==0.10.3.post1
    - soupsieve==2.3.2.post1
    - sox==1.4.1
    - speechbrain==0.5.13
    - tabulate==0.8.10
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - terminado==0.16.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tokenizers==0.12.1
    - torch==1.10.1+cu111
    - torch-optimizer==0.3.0
    - torch-stoi==0.1.2
    - torchaudio==0.10.1+cu111
    - torchmetrics==0.7.0
    - torchvision==0.11.2+cu111
    - tornado==6.2
    - tqdm==4.64.0
    - traitlets==5.4.0
    - transformers==4.20.1
    - typing-extensions==4.3.0
    - urllib3==1.26.11
    - wandb==0.12.21
    - wavencoder==0.1.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.2.0
    - whisper==1.0
    - widgetsnbextension==4.0.3
    - yarl==1.7.2
    - zipp==3.8.1
